version: "3.8"

services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
volumes:
  postgres_data_volume:
